# Generated by Django 3.2.9 on 2021-12-03 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('committee_name', models.CharField(max_length=100)),
                ('committee_members_limit', models.IntegerField()),
                ('committee_amount_per_month', models.IntegerField(default=0)),
                ('committee_month_period', models.IntegerField(default=0)),
                ('committee_amount_limit', models.IntegerField(null=True)),
                ('committee_starting_date', models.DateTimeField()),
                ('committee_ending_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Committee',
                'verbose_name_plural': 'Committees',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants_paid_status', models.BooleanField(default=False)),
                ('participants_amount_paid', models.IntegerField()),
                ('participants_payment_slip', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('participants_committee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.committee')),
                ('participants_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
            },
        ),
        migrations.AddField(
            model_name='committee',
            name='committee_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.profile'),
        ),
    ]
